### ISSUE TITLE
2017. 8. 17 meeting

### ISSUE THREAD

**Issue by jehoons** [jehoons/sbie_weinberg#64]
이번주 

*춘경* 시너지 확인, 약물 유사성 시뮬레이션 수행 예정 

*종훈* SFA알고리즘 

*영현* UI 구성... HOW?

**Comment by choonlog** [comment]
[170817_플랫폼팀_이춘경.pptx](https://drive.google.com/open?id=0B1xFxkWRHv8aMXp6RGw2OTAyYU0)

**Comment by jehoons** [comment]
폐암네트워크 모델 - StableMotifAnalysis?

**Comment by choonlog** [comment]
[170818_Lung cancer ChEMBL_ID_이춘경.xls](https://drive.google.com/open?id=0B1xFxkWRHv8ad3lkdldLTUFGRjQ)

**Comment by jehoons** [comment]
약물유사성 프로그램코드 
https://github.com/jehoons/sbie_optdrug2/tree/master/results/table_s2

기타 참고문헌
[Tsherniak et al_2017_Defining a Cancer Dependency Map.pdf](https://github.com/jehoons/sbie_weinberg/files/1247700/Tsherniak.et.al_2017_Defining.a.Cancer.Dependency.Map.pdf)
