### ISSUE TITLE
white paper 작성

### ISSUE THREAD

**Issue by jehoons** [jehoons/sbie_weinberg#65]
국책과제의 화이트페이퍼를 작성해야 합니다. 팀원들은 해당 내용을 작성해주시길 바랍니다. 작성시에는 아래 참고자료를 살펴봐 주세요. 각자 작성한 내용은 아래에 코멘트를 달아주세요. 

[white-paper-rev1.docx](https://github.com/jehoons/sbie_weinberg/files/1275861/white-paper-rev1.docx)

참고자료 
[white paper - dream2015_rev21.docx](https://github.com/jehoons/sbie_weinberg/files/1275850/white.paper.-.dream2015_rev21.docx)

**Comment by choonlog** [comment]
'4-1. 상태끌개 분석 모듈과', '첨부 : 프로그램 코드' 부분을 작성하였습니다.

[화이트페이퍼v2(170921_이춘경)](https://drive.google.com/open?id=0B1xFxkWRHv8aSnF3Sm1Zd2FIRjQ)

**Comment by hanyh0807** [comment]
시나리오 부분 작성하였습니다
[화이트페이퍼v2(영현_시나리오).zip](https://github.com/jehoons/sbie_weinberg/files/1323361/v2._.zip)
